import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBer from "./components/NavBer";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-11/12 mx-auto`}
      >
        <NavBer></NavBer>
        <main className="px-2">
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
